server.port=8080

# GitHub API
github.api.url=https://api.github.com

# LeakCheck Public API
leakcheck.api.url=https://leakcheck.net/api/public

# EmailRep.io (Anonymous mode)
emailrep.api.url=https://emailrep.io

# Gravatar base URL
gravatar.base.url=https://www.gravatar.com/avatar

# Pastebin search URL (PSBDMP)
pastebin.search.url=https://psbdmp.ws/api/v2/search

# Groq API (AI Analysis)
groq.api.url=https://api.groq.com/openai/v1
groq.api.key=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
